name: Build Image

on:
  push:
    branches: [ master ]    

jobs:    
    build:      
      name: Build Go
      runs-on: ubuntu-latest
      steps:         
        - uses: actions/checkout@v2                   
        - name: docker compose build                  
          working-directory: ./container
          run: docker-compose build
        - name: docker login
          run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        - name: docker tag
          run: |
                  docker tag katarilab/ubuntu-diagnostic katarilab/ubuntu-diagnostic:latest
                  docker tag katarilab/ubuntu-diagnostic katarilab/ubuntu-diagnostic:${{ github.sha }}                  
                  docker push katarilab/ubuntu-diagnostic
    